### ISSUE TITLE
Allow using LOGOS with newer versions of Python by removing cbcpy

### ISSUE THREAD

**Issue by joshua-cogliati-inl** [idaholab/LOGOS#41]
**Is your feature request related to a problem? Please describe.**
cbcpy is not available on python versions newer than 3.7

**Describe the solution you'd like**
Remove cbcpy

**Additional context**
cbcpy was added to try and fix windows, but it doesn't work:
```
08-Aug-22 09:57:38 pyomo.opt            ERROR    Solver (cbc) returned non-zero return code (3221225781)

Traceback (most recent call last):

  File "C:\Git\opt\build_root\raven\plugins\LOGOS\src\logos_main.py", line 72, in <module>

    modelInstance.run()

  File "C:\Git\opt\build_root\raven\plugins\LOGOS\src\CapitalInvestments\PyomoModels\ModelBase.py", line 294, in run

    results = opt.solve(model, load_solutions=False, tee=self.tee, **{'use_signal_handling':False})

  File "C:\Users\cogljj\.conda\envs\raven_libraries\lib\site-packages\pyomo\opt\base\solvers.py", line 597, in solve

    "Solver (%s) did not exit normally" % self.name)

pyomo.common.errors.ApplicationError: Solver (cbc) did not exit normally
```

See for example: https://civet.inl.gov/job/1145673/

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by wangcj05** [comment]
issue closure checklist is good.
